### ISSUE TITLE
Dashboard Layout 

### ISSUE THREAD

**Issue by beth-german** [pulibrary/tigerdata-app#995]
Dashboard Layout - components being worked on

Updates to the dashboard:

We are changing the above design to be more self-explanatory and easier to navigate. The dashboard will now include two levels of tabbed navigation - L1 and L2.

L1 : Projects

L2: All
L2: Active
L2: Pending
L1: Activity

L2: All
L2: By Projects
![image](https://github.com/user-attachments/assets/8ed118d6-dfa9-4496-b143-377cb992c685)

This is how we imagine the dashboard would look like:
![image](https://github.com/user-attachments/assets/51a6319c-121a-4a06-bdee-80e759cf41e4)

## Components of this Epic (in priority order)
- [ ] **(Epic)** Project tab on dashboard: https://github.com/pulibrary/tigerdata-app/issues/1025
- [ ] Activity Tab https://github.com/pulibrary/tigerdata-app/issues/1050

## Related Components - Tigerdata-app
- [x] Tabbed Navigation component: https://github.com/pulibrary/tigerdata-app/issues/982 
- [ ] **(Epic)** Monitoring Panel https://github.com/pulibrary/tigerdata-app/issues/1051 
- [ ] Project table notifications https://github.com/pulibrary/tigerdata-app/issues/1026 

## Related Components - AUX 
- [x] Dashboard Tabbed Navigation https://github.com/pulibrary/aux/issues/15
- [x] Monitoring Panel https://github.com/pulibrary/aux/issues/16
- [x]  Active Projects Tab Active Projects Tab and Table  https://github.com/pulibrary/aux/issues/19 - see project tab
- [x] Project Requests Tab Project Requests Tab and Table  https://github.com/pulibrary/aux/issues/20 - see project tab
- [x]  Downloads Tab https://github.com/pulibrary/aux/issues/21 - see project tab
- [x] - All Activity Tab https://github.com/pulibrary/aux/issues/22
- [x] - Recent Activity Box https://github.com/pulibrary/aux/issues/17
- [x] - Downloads Box https://github.com/pulibrary/aux/issues/18
- [x] - Tab notifications https://github.com/pulibrary/aux/issues/23
- [x] Project Table notifications https://github.com/pulibrary/aux/issues/24

**Comment by matthewjchandler** [comment]
What remains on this is being reformulated for the Beta Release
